[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "42yK1ZKUzMi1PCLTra7SXNLRGJRVSnLbR5neGj9fFJtN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"

[hooks]
