[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "DZ6dbiagaYka6FznFgLGEnBRhbbosjhod4Wwou1z3EcK"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"

[hooks]
