[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "DXZ1gUBaHsj5cKAfRGZjqYigWF7wv1Js2aHKwKVYtUVA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-sbf"

[hooks]
